In [2]:
import numpy as np

In [92]:
m1 = np.zeros((4,5), dtype=np.float32)
m2 = np.array([[[1,1],[2,2],[45,45]],[[3,3],[4,4],[23,23]] ])

In [93]:
m1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [94]:
m2

array([[[ 1,  1],
        [ 2,  2],
        [45, 45]],

       [[ 3,  3],
        [ 4,  4],
        [23, 23]]])

In [95]:
m2 = m2.sum(axis=0)

In [96]:
m2 = m2.sum(axis =0)

In [97]:
m2

array([78, 78])